### PR TITLE
build.gradle changes for distribution

### PR DESCRIPTION
**Pull request by juliantoledo**
I made changes to build.gradle for distribution in maven central, etc. for #9 

It's publish here:
https://bintray.com/juliantoledo/Maven/archive-patcher

I still need to link it to JCenter.

### CODE REVIEW

**Comment by andrewhayden** [comment]
Sounds good to me. @canamaria , what do you think? I know you have mentioned a desire to upstream a bugfix or two, do you want to do that before we land this change to put it into Maven?

Moving forward, @juliantoledo , can you document what process is needed to update the version in Maven after bugfixes are made in the future, i.e. for incrementing the version?

**Comment by juliantoledo** [comment]
@andrewhayden sure, I will document it. I still need to generate a sources jar, and optionally a javadoc jar, do be able to link it from JCenter.

**Comment by canamaria** [comment]
Hi everyone,

Yes, there is one internal bug fix in particular that we should upstream
before we put this into Maven. I will look into it today and let you know
as soon as it's in.

Thanks,
Ana

**Comment by juliantoledo** [comment]
@andrewhayden @canamaria I fixed the jar generation to include sources and javadoc. I also push the sync to JCenter (that should take few hours/days)
https://bintray.com/juliantoledo/Maven/archive-patcher

**Comment by juliantoledo** [comment]
Published: https://bintray.com/juliantoledo/Maven/archive-patcher

**Comment by juliantoledo** [comment]
Yes, please.

**Pull request merged**
